# -*- coding: utf-8 -*-
"""youtube_video_download.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BtLlMD8lW9rAyOpI0ep_-FfvpJu_vQit
"""

from pytube import YouTube
from moviepy.editor import *

def download_youtube_video(url, output_path):
    try:
        yt = YouTube(url)
        video = yt.streams.filter(file_extension='mp4').first()
        print("Downloading video...")
        video.download(output_path)
        print("Video downloaded successfully!")
        return video.default_filename
    except Exception as e:
        print("Error:", str(e))
        return None

def convert_video_to_audio(video_file, output_path):
    try:
        video = VideoFileClip(video_file)
        audio = video.audio
        print("Converting video to audio...")
        audio.write_audiofile(output_path)
        print("Audio converted and downloaded successfully!")
    except Exception as e:
        print("Error:", str(e))

# Set output directory in Colab environment
output_directory = "/content"

# Ask for YouTube URL
youtube_url = input("Enter the YouTube video URL: ")

# Download YouTube video
video_filename = download_youtube_video(youtube_url, output_directory)

if video_filename:
    # Ask whether to convert to audio
    convert_to_audio = input("Do you want to convert the video to audio? (yes/no): ").lower()

    if convert_to_audio == "yes":
        # Convert video to audio
        output_audio_file = f"{output_directory}/audio.mp3"
        convert_video_to_audio(f"{output_directory}/{video_filename}", output_audio_file)
    elif convert_to_audio == "no":
        print("Video downloaded successfully!")
    else:
        print("Invalid input. Please enter 'yes' or 'no'.")

